### ISSUE TITLE
OperationのBrowseNodeLookupを追加したい

### ISSUE THREAD

**Issue by ryosuke-endo** [r7kamura/rapa#7]
## 目的

`BrowseNodeLookup`を使用する

## 備考

現状できないと考えています。

`Operation`に`BrowseNodeLookup`がないためです。

新しく機能として作成する予定ですが、何かまずいことはありますでしょうか？:bow:

ほしい理由は、`NewReleases`が使用したいからです！

**Comment by r7kamura** [comment]
特にまずいことはなさそうです。自分では使う予定が無かったので、これまでつくっていませんでした

**Comment by ryosuke-endo** [comment]
>自分では使う予定が無かったので、これまでつくっていませんでした

なるほど:memo:

では、別途プルリクを作成します:bow:

ありがとうございます！

**Comment by r7kamura** [comment]
https://github.com/r7kamura/rapa/pull/8 で追加してもらいました、ありがとうございます 🙏
